# Generated by Django 5.2.5 on 2025-08-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='location',
        ),
        migrations.AddField(
            model_name='companionrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='price_for_one_person',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companionrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
